In [1]:
# %matplotlib inline
import numpy as np

# %reload_ext autoreload
# %autoreload 2

import pyradi.ryplot as ryplot

In [2]:
p = ryplot.Plotter(1,1,1)
a = np.linspace(0,10,100)
p.plot(1,a,a)

p.saveFig(filename='mpl.png', dpi=300, bbox_inches='tight', pad_inches=0.1, useTrueType=True)



In [8]:
a = np.ones((5,3))
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [9]:
a[:,2] -= 5
print(a)

[[ 1.  1. -4.]
 [ 1.  1. -4.]
 [ 1.  1. -4.]
 [ 1.  1. -4.]
 [ 1.  1. -4.]]


In [1]:
from IPython.display import Latex
Latex(r"""\begin{eqnarray}
\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} & = \frac{4\pi}{c}\vec{\mathbf{j}} \\
\nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\
\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\
\nabla \cdot \vec{\mathbf{B}} & = 0 
\end{eqnarray}""")

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>